name: Update Cuaca BMKG (JSON)

on:
  schedule:
    - cron: '0 */3 * * *'  # jalan tiap 3 jam
  workflow_dispatch:

jobs:
  update-cuaca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo cuaca-bmkg
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Jalankan skrip Python
        run: python update_cuaca.py

      - name: Clone repo GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/pradipta570/pradipta570.github.io.git pages
     
      - name: Salin cuaca.txt ke repo GitHub Pages dan commit jika ada perubahan
        run: |
          cp cuaca.txt pages/
          cd pages
          git add cuaca.txt
          # Hanya commit & push jika ada perubahan
          if ! git diff --cached --quiet; then
            git commit -m "Update cuaca.txt otomatis"
            git push
          else
            echo "Tidak ada perubahan pada cuaca.txt, skip commit."
          fi
