name: Update Cuaca

on:
  schedule:
    - cron: "*/10 * * * *"  # Setiap 10 menit
  workflow_dispatch:       # Bisa dijalankan manual juga

jobs:
  update-cuaca:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Jalankan script update cuaca
      run: python cuaca.py

- name: Commit dan Push file cuaca.json
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@github.com"
    git add cuaca.json
    git commit -m "Update otomatis cuaca.json"
    git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
