name: Update Cuaca

on:
  schedule:
    - cron: '*/10 * * * *'  # tiap 10 menit
  workflow_dispatch:       # bisa juga dijalankan manual

jobs:
  update-cuaca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Jalankan script update cuaca
        run: python cuaca.py

      - name: Commit dan push jika ada perubahan
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add cuaca.json
          git commit -m "🔄 Update cuaca otomatis" || echo "No changes to commit"
          git push
